### ISSUE TITLE
removed model can't recover

### ISSUE THREAD

**Issue by goldenxinxing** [star-whale/starwhale#1136]
**Describe the bug**
`(starwhale) ➜  mnist git:(main) swcli model remove mnist/version/g42tkmrxme3g
continue to delete? [y/N]: y
👏 do successfully
(starwhale) ➜  mnist git:(main) swcli model recover mnist/version/g42tkmrxme3g
🤿 failed to run, reason:src:/home/star_g/.starwhale/self/model/.recover/mnist/g4/g42tkmrxme3g.swmp not found`

**To Reproduce**

**Expected behavior**

**Environment**

**Comment by tianweidut** [comment]
![image](https://user-images.githubusercontent.com/590748/190960148-7963a7c0-31f9-4f27-ba8a-165c1b8688c6.png)

recover model/runtime/dataset with the full version, not short version

**Comment by tianweidut** [comment]
https://github.com/star-whale/starwhale/issues/1247
