### ISSUE TITLE
can't use “swcli model info mnist/version/latest” after removed the “latest” model

### ISSUE THREAD

**Issue by goldenxinxing** [star-whale/starwhale#1138]
**Describe the bug**
can't use “swcli model info mnist/version/latest” after removed the “latest” model

**To Reproduce**

1. swcli model remove mnsit/verison/latest
2. swcli model info mnist/version/latest
then there will throw an error:not found

**Expected behavior**
the latest tag can be used to the newest version which already exists

**Environment**

**Comment by tianweidut** [comment]
`latest` is a tag, not the git `HEAD~0`.
