### ISSUE TITLE
dataset history error when use cmd 'swcli dataset history DATASET'

### ISSUE THREAD

**Issue by goldenxinxing** [star-whale/starwhale#1160]
**Describe the bug**
error log:
![image](https://user-images.githubusercontent.com/24869618/189127896-c58f746c-9c9b-4fce-be65-554ec4f5ed89.png)

**To Reproduce**

**Expected behavior**

**Environment**

**Comment by tianweidut** [comment]
![image](https://user-images.githubusercontent.com/590748/191003031-644c0ef0-f3e2-4d0f-add2-7f64bba1f2b6.png)
fixed by https://github.com/star-whale/starwhale/pull/1242
