### ISSUE TITLE
The job status is Success, but it failed actually

### ISSUE THREAD

**Issue by lijing-susan** [star-whale/starwhale#1166]
**Describe the bug**
![image](https://user-images.githubusercontent.com/101299635/189100492-ac3c82ef-85cb-467d-8f02-be84a35a3c57.png)

![image](https://user-images.githubusercontent.com/101299635/189100427-163deeb5-a09c-4938-86d2-6d2b22578611.png)

**To Reproduce**

-taskID： ef615812-6d1a-4e40-9a92-7d6c1dab060f

**Expected behavior**

**Environment**

**Comment by tianweidut** [comment]
https://github.com/star-whale/starwhale/pull/1248
