### ISSUE TITLE
eval can't recover when an evalJob was removed

### ISSUE THREAD

**Issue by goldenxinxing** [star-whale/starwhale#1168]
**Describe the bug**
![image](https://user-images.githubusercontent.com/24869618/189268168-dfeecb60-9d20-44d6-a770-f9e9985b86d2.png)
![image](https://user-images.githubusercontent.com/24869618/189268188-3fa796ef-65ba-4071-8333-62d15be530d1.png)

**To Reproduce**

1. swcli eval remove {version}
2. swcli eval recover {version}

**Expected behavior**

**Environment**

**Comment by tianweidut** [comment]
![image](https://user-images.githubusercontent.com/590748/191003476-6264384f-dece-49f8-86c6-5d46dd45eeb3.png)

swcli only supports recovery with the full version name.

**Comment by tianweidut** [comment]
https://github.com/star-whale/starwhale/issues/1247
