### ISSUE TITLE
Unified the dataset table name when copy

### ISSUE THREAD

**Issue by goldenxinxing** [star-whale/starwhale#1731]
**Describe the bug**
It will have different table names when copy dataset to cloud use bellow commands: 
- swcli dataset copy ucf101/version/latest cloud://e2e0128/project/1(table name is 'project/1/...')
- swcli dataset copy ucf101/version/latest cloud://e2e0128/project/starwhale(table name is 'project/starwhale/...')
But it is unified on the cloud with the same name 'project/starwhale/...'.
And it will lead error when dataset load data: `ai.starwhale.mlops.exception.SwValidationException: invalid request on subject Starwhale Internal DataStore
invalid table name project/starwhale/dataset/ucf101/7m/7mguzpokk7ez3xssi4l3rk4zhesd6we3dvyj4aot/meta`,and the reason is that the real name is 'project/1/dataset/ucf101/7m/7mguzpokk7ez3xssi4l3rk4zhesd6we3dvyj4aot/meta'

![image](https://user-images.githubusercontent.com/24869618/215261865-34e5a5bd-4092-4303-bf74-fc824e87b3ec.png)
![image](https://user-images.githubusercontent.com/24869618/215261873-c623b9c7-fea9-42ad-9bda-b2f364d8bd69.png)
![image](https://user-images.githubusercontent.com/24869618/215261881-3100c6ff-e867-4f7d-8e52-9dfa3976ee3e.png)
![image](https://user-images.githubusercontent.com/24869618/215261889-22596c23-6413-4ab5-b112-59ae72008aac.png)

**To Reproduce**

**Expected behavior**

**Environment**

**Comment by goldenxinxing** [comment]
The simple way to fix it is change the upload logic [upload code](https://github.com/star-whale/starwhale/blob/bfc81c829441fca7bab6c183f7976c5204f01c25/server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/upload/DatasetUploader.java#L242) from datasetVersionEntity = from(projectEntity.getProjectName(), datasetEntity, manifest); to datasetVersionEntity = from(uploadRequest.getProject(), datasetEntity, manifest);
But it will have a new problem when user use projectName again(because client use projectName to update datastore)
Environment.

**Comment by anda-ren** [comment]
> The simple way to fix it is change the upload logic [upload code](https://github.com/star-whale/starwhale/blob/bfc81c829441fca7bab6c183f7976c5204f01c25/server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/upload/DatasetUploader.java#L242) from` datasetVersionEntity = from(projectEntity.getProjectName(), datasetEntity, manifest);` to `datasetVersionEntity = from(uploadRequest.getProject(), datasetEntity, manifest);` **But it will have a new problem when user use projectName again(because client use projectName to update datastore) Environment.**

It seems like a bug for client. Changeing server to workaround for that is not proper I think.

**Comment by goldenxinxing** [comment]
> > The simple way to fix it is change the upload logic [upload code](https://github.com/star-whale/starwhale/blob/bfc81c829441fca7bab6c183f7976c5204f01c25/server/controller/src/main/java/ai/starwhale/mlops/domain/dataset/upload/DatasetUploader.java#L242) from` datasetVersionEntity = from(projectEntity.getProjectName(), datasetEntity, manifest);` to `datasetVersionEntity = from(uploadRequest.getProject(), datasetEntity, manifest);` **But it will have a new problem when user use projectName again(because client use projectName to update datastore) Environment.**
> 
> It seems like a bug for client. Changing server to workaround for that is not proper I think.

yes, another way is return the tablename from the response which is returned at first uploading, then datasetTablar receive tableName but not project. cc @tianweidut
