### ISSUE TITLE
display system version on UI

### ISSUE THREAD

**Issue by anda-ren** [star-whale/starwhale#180]
**Is your feature request related to a problem? Please describe.**
user don't know what the version of SW is when he/she is attempting to make a bug report

**Describe the solution you'd like**

1. make the version info avaliable in the OS envirenment variables when building controller and agent images.
2. agent reads the OS ENV variable and reports it's version info to controller
3. controller reads the OS ENV and agents' reports 
4. controller offers an API to UI and cli to expose these version info through

**Comment by anda-ren** [comment]
UI part has not been implemented

**Comment by waynelwz** [comment]
done
