### ISSUE TITLE
some dataset can't view properlly on cloud

### ISSUE THREAD

**Issue by anda-ren** [star-whale/starwhale#1854]
**Describe the bug**
- [image-net](https://cloud.starwhale.cn/projects/12/datasets/35/versions/60/files)
- [gtsrb](https://cloud.starwhale.cn/projects/12/datasets/34/versions/59/files)
- [wider_face](https://cloud.starwhale.cn/projects/12/datasets/44/versions/70/files)
- [svhn](https://cloud.starwhale.cn/projects/12/datasets/43/versions/69/files)
- [stanford_cars](https://cloud.starwhale.cn/projects/12/datasets/42/versions/68/files)
- [nmt](https://cloud.starwhale.cn/projects/12/datasets/39/versions/64/files)
- [flickr8k](https://cloud.starwhale.cn/projects/12/datasets/33/versions/58/files)

**To Reproduce**

**Expected behavior**

**Environment**

**Comment by waynelwz** [comment]
done
