### ISSUE TITLE
conda export sometimes omit starwhale package

### ISSUE THREAD

**Issue by tianweidut** [star-whale/starwhale#208]
**Describe the bug**
- conda export omit starwhale python package randomly. 
- Reproduce Case:  conda cannot export editable starwhale.

**Expected behavior**
conda export **MUST** include starwhale, if not , it will lead to import error in ppl/cmp phase.

**Proposal**
add some doc and console warnings

**Comment by goldenxinxing** [comment]
Does this bug only exist in development mode？
