### ISSUE TITLE
swcli dataset copy hungup when the dataset is big

### ISSUE THREAD

**Issue by anda-ren** [star-whale/starwhale#2145]
**Describe the bug**
![image](https://user-images.githubusercontent.com/89630947/234500782-eb3a1209-38ee-4d49-aa43-e172c2b09cc9.png)
It doesn't raise any error or finish with a success tip for tens of miniutes

**To Reproduce**
grailqa dataset

**Expected behavior**
show some tips or make it faster
**Environment**

**Comment by jialeicui** [comment]
it makes the loading slow because of the type inference of huge data

https://github.com/star-whale/starwhale/blob/8aeaf0e3384a56c5f82ebced371a1c3eef0b8c9b/client/starwhale/api/_impl/data_store.py#L599-L605
