### ISSUE TITLE
swcli runtime build -s could not freez pypi package from github using conda env

### ISSUE THREAD

**Issue by anda-ren** [star-whale/starwhale#2156]
**Describe the bug**
swcli runtime build -s could not free pypi package from github using conda env

**To Reproduce**

```bash
conda env create -n x
pip install git+https://github.com/huggingface/peft.git@e536616888d51b453ed354a6f1e243fecb02ea08
swcli runtime build -s
swcli runtime restore x
error occurs
```

**Expected behavior**
runtime could install git+https://github.com/huggingface/peft.git@e536616888d51b453ed354a6f1e243fecb02ea08

**Relate issue**
https://github.com/conda/conda/issues/10320

**Comment by tianweidut** [comment]
https://github.com/star-whale/starwhale/pull/2164
