### ISSUE TITLE
prevent users from building runtimes that could not be restored

### ISSUE THREAD

**Issue by anda-ren** [star-whale/starwhale#2202]
**Current Behavior**
There is no explicit tip for users to know how to resolve the error when they can't restore a runtime in the case that PyPI package versions conflict with each other

**Proposed Behavior**
When the user is building a runtime that cannot be restored, swcli should raise an exception and provide instructions on how to build a restorable one

**Comment by tianweidut** [comment]
![image](https://github.com/star-whale/starwhale/assets/590748/55c3612d-1808-4fa4-8f48-6388ac06c2cf)

```
icetk==0.0.7
protobuf==3.20
```
