### ISSUE TITLE
populate more context information to users' code

### ISSUE THREAD

**Issue by anda-ren** [star-whale/starwhale#2203]
**Current Behavior**
There is limited information that users can take advantage of when they embed their code into Starwhale's framework, such as @evaluation.predict. When users want to fit their model to multiple datasets, it can be difficult for them to determine which dataset the data belongs to

```python
@evaluation.predict
def ppl(data: dict, **kw):
    text = data["text"] // text=data["query"]?text=data["question"]?text=data["question"]
```

**Proposed Behavior**
populate more context information to users' code

**Comment by tianweidut** [comment]
https://github.com/star-whale/starwhale/pull/2209
