### ISSUE TITLE
`encodeWithType` parameter in datastore `scaneTable` api should default to True

### ISSUE THREAD

**Issue by anda-ren** [star-whale/starwhale#2204]
**Current Behavior**
`encodeWithType` parameter in datastore `scaneTable` api defaults to `False`

**Proposed Behavior**
Since Datastore is designed to be typeless, the API it populates should default to typeless, which means the encodeWithType parameter should default to true.

**Solution Proposal**

**Comment by jialeicui** [comment]
#2200
