### ISSUE TITLE
support web terminal for evaluation jobs

### ISSUE THREAD

**Issue by tianweidut** [star-whale/starwhale#2213]
**Proposed Behavior**
When the user config `debug=True` in the web console, the job task will not exit automatically, making the user debug by the web terminal.
In addition, `vscode` and `jupyter notebook` are good debugging tools for users.  

cc @anda-ren  @jialeicui

**Comment by waynelwz** [comment]
vscode is ready

**Comment by jialeicui** [comment]
Close with #2313
