### ISSUE TITLE
add image classification example

### ISSUE THREAD

**Issue by tianweidut** [star-whale/starwhale#230]
**Current Behavior**
only mnist.

**Proposed Behavior**
 - [ ] add 2-3 image classfication examples, use pytorch/tensorflow/sklearn lib
 - [ ] tune sdk and ppl/cmp report 

**Solution Proposal**
 - https://github.com/pytorch/serve/tree/master/examples/image_classifier
 - https://towardsdatascience.com/exploring-classifiers-with-python-scikit-learn-iris-dataset-2bcb490d2e1b

**Comment by anda-ren** [comment]
done
