### ISSUE TITLE
add object detection example

### ISSUE THREAD

**Issue by tianweidut** [star-whale/starwhale#232]
**Current Behavior**
no object detection example. 

**Proposed Behavior**
- [ ] add 2-4 object detection example
- [ ] tune sdk
- [ ] tune ppl amd cmp report 

**Solution Proposal**
- https://github.com/pytorch/serve/tree/master/examples/object_detector

**Comment by alexkumar-nuub** [comment]
Try adding object detection of face mask in real time . Easy one .

**Comment by xuchuan** [comment]
> Try adding object detection of face mask in real time . Easy one .

Thank you very much. We're still working on basic examples which can be done with public data sets. Real-time detection is not supported in the current version.
