### ISSUE TITLE
job hanging when pause then resume

### ISSUE THREAD

**Issue by waynelwz** [star-whale/starwhale#272]
**Describe the bug**
Job no response

**To Reproduce**
1. new job
2. pause
3. resume

**Expected behavior**
1. job running

**Environment**
 follow: http://console.pre.intra.starwhale.ai/projects/1/jobs/66/tasks

**Comment by anda-ren** [comment]
due to partially work of issue182
- [ ] #182 
now the work is implemented both by controller and agent.
issue closed
