### ISSUE TITLE
Task rerun success but status is running

### ISSUE THREAD

**Issue by goldenxinxing** [star-whale/starwhale#2933]
**Describe the bug**

http://e2e-20231023.pre.intra.starwhale.ai/projects/1/jobs/7/tasks

![bf717a76-2944-4c54-ad2f-1cd660c0d568](https://github.com/star-whale/starwhale/assets/24869618/ffefce28-a6ca-4e15-8c50-87a2ff779820)

![3a1ae4a4-59f0-44e4-bc30-97964a2d9f59](https://github.com/star-whale/starwhale/assets/24869618/d42e705b-8c33-482b-b720-93e5a5213746)

![78d973c6-670c-4810-83ca-1c4210ddb0af](https://github.com/star-whale/starwhale/assets/24869618/98c2062f-9133-4f80-8e77-90bdb099c0e5)

**To Reproduce**

**Expected behavior**

**Environment**

**Comment by goldenxinxing** [comment]
tow controller exists.

**Comment by anda-ren** [comment]
when we update controller deployment, there will be a while that two controller instances are running simultaneously. The old controller dispatches a new run while the new controller doesn't aware of that. When the old goes down, the new controller will say the new run is illegal and reject to update status.
