### ISSUE TITLE
status FAIL task can't open log

### ISSUE THREAD

**Issue by anda-ren** [star-whale/starwhale#294]
**Describe the bug**
status FAIL task can't open log
http://console.pre.intra.starwhale.ai/projects/1/jobs/75/tasks

**To Reproduce**
make job fail, click `View Log` button

**Expected behavior**
log files are shown

**Environment**
http://console.pre.intra.starwhale.ai

**Comment by waynelwz** [comment]
issue has been fixed, checkout
