### ISSUE TITLE
您好，我这边有4张gpu卡,想调用gpu,希望能得到帮助

### ISSUE THREAD

**Issue by zhengxiangrong** [star-whale/starwhale#3142]
我这边有一张4090的卡，想知道如何配置才能将我的gpu使用起来做predict，serving等
<img width="683" alt="1732174324640" src="https://github.com/user-attachments/assets/d2848b26-104d-4787-81ad-99564994d82b">

**Comment by jialeicui** [comment]
不太清楚您做到哪一步了, 我先说一下我理解的步骤:  
1. 首先, 保证您的环境里启动的 container 能摸到 GPU, 也就是能在 container 里执行 `nvidia-smi` (通常按照 [这个文档](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html) 应该就可以配置好)  
2. 然后在 runtime 里指定需要的 cuda 版本, 可以参考 https://starwhale.cn/docs/runtime/yaml#%E5%AE%8C%E6%95%B4%E5%AD%97%E6%AE%B5%E7%A4%BA%E4%BE%8B  
跑起来的代码就可以调用 GPU 了
