### ISSUE TITLE
在前端页面创建serving 任务时，前端页面显示gradio有问题

### ISSUE THREAD

**Issue by zhengxiangrong** [star-whale/starwhale#3146]
前端页面显示和gradio格式不一致，如下图
<img width="827" alt="1732781981895" src="https://github.com/user-attachments/assets/49f3a439-4b42-436b-929f-157d7a414334">

**Comment by jialeicui** [comment]
猜测大概率是某些 css 拉取失败了, 浏览器配置好了自动科学上网么? gradia 生成的前端会去自己配好的cdn拉数据

**Comment by jialeicui** [comment]
<img width="657" alt="image" src="https://github.com/user-attachments/assets/f9d8872e-256b-4059-86cd-f3b30d295240">

**Comment by zhengxiangrong** [comment]
嗯嗯，好的
