### ISSUE TITLE
您好，我想修改mysql为云端的服务，不想用本地的mysql镜像

### ISSUE THREAD

**Issue by zhengxiangrong** [star-whale/starwhale#3147]
我修改了compose.tmpl 文件如下图所示，但是好像不起作用，服务启动时还是在使用mysql的docker镜像
![Uploading 61cf27f6c23dbe82ad055c5bb6fe556.jpg…]()

**Comment by zhengxiangrong** [comment]
![Uploading 61cf27f6c23dbe82ad055c5bb6fe556.jpg…]()

**Comment by jialeicui** [comment]
您的图好像没有上传完, 您可以重新贴一下图或者文件内容么?

**Comment by zhengxiangrong** [comment]
![1](https://github.com/user-attachments/assets/2be32997-57fe-4af1-a02c-457ddce4ee5c)

**Comment by jialeicui** [comment]
这个模板是 swcli 用来 render 最终使用的 docker-compose.yaml 的, 相关的环境变量会被覆盖  
您可以试试基于 sw 目录生成之后的 yaml 来修改 , 直接用 docker compose 启动就可以, 通常在 `$HOME/.starwhale/.server/docker-compose.yaml`

**Comment by zhengxiangrong** [comment]
嗯嗯，那要怎么修改才能把mysql换成云端的呢？

**Comment by zhengxiangrong** [comment]
<img width="659" alt="2" src="https://github.com/user-attachments/assets/5e01d0e4-f0d6-4efc-ba82-65dcdd2d8fd6" />
我把db的image去了，然后加了SW_METADATA_STORAGE_DB=mlops，改了SW_METADATA_STORAGE_IP，SW_METADATA_STORAGE_USER，SW_METADATA_STORAGE_PASSWORD这样改对吗？

**Comment by jialeicui** [comment]
嗯, 您可以参考这个配置  
https://github.com/star-whale/starwhale/blob/336b5876fbaabd2f1fe4b5ea2adc6744cd47b260/server/controller/src/main/resources/application.yaml#L160-L166

**Comment by zhengxiangrong** [comment]
您好我修改了compose.tmpl文件，但是服务器无法启动，无法将mysql换成云端的服务。请问能按照上面给的测试文件办我修改一下嘛？目前mysql使用ip地址为127.0.0.1（测试可以后会换成云端ip）,端口3306，密码 My:S3cr3t/，mysql 用户为root, 数据库名称为mlops


1
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "star-whale/starwhale"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月22日(星期天) 晚上10:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [star-whale/starwhale] 您好，我想修改mysql为云端的服务，不想用本地的mysql镜像 (Issue #3147)





 
Closed #3147 as completed.

**Comment by zhengxiangrong** [comment]
您好我修改了compose.tmpl文件，但是服务器无法启动，无法将mysql换成云端的服务。请问能按照上面给的测试文件办我修改一下嘛？目前mysql使用ip地址为127.0.0.1（测试可以后会换成云端ip）,端口3306，密码 My:S3cr3t/，mysql 用户为root, 数据库名称为mlops
<img width="260" alt="444" src="https://github.com/user-attachments/assets/fdebd278-c92f-4735-9872-3d04d0c2b77d" />
<img width="619" alt="555" src="https://github.com/user-attachments/assets/4654f09b-6279-4ef6-9b37-4666dee9c834" />

**Comment by jialeicui** [comment]
修改这些就可以了, 您可以试下, 为了确认一下问题在哪儿:
- docker compose 起来之后进去 server 的 container 里看下环境变量是不是您预期的值
- 用预期的各种参数在有 mysql client 的 container 里(比如一块把 mysql server 也起来) 尝试连一下您想要连接的那个云端 server, 看下是不是通的
