### ISSUE TITLE
online log doesn't update timely

### ISSUE THREAD

**Issue by anda-ren** [star-whale/starwhale#406]
**Describe the bug**
the log of running task doesn't update timely

**To Reproduce**

1. create one cifar10 job
2. when task running, click view log
3. the log will never update
4. after job success , the log for the task is still what is at the beginning

**Expected behavior**
- the log update timely
- the log will close automiclly when the task is finished

**Environment**
http://console.pre.intra.starwhale.ai/

**Comment by waynelwz** [comment]
![image](https://user-images.githubusercontent.com/100347187/169967000-aecf6ce8-1f37-421a-87c7-87d63a5cd35a.png)

empty log return from ws

cc @goldenxinxing
