### ISSUE TITLE
failed task is  shown success

### ISSUE THREAD

**Issue by anda-ren** [star-whale/starwhale#407]
**Describe the bug**
failed task is  shown success

**To Reproduce**
create a job same as job 16,
http://console.pre.intra.starwhale.ai/projects/1/jobs/16/tasks

**Expected behavior**
failed task status should be failed

**Environment**
http://console.pre.intra.starwhale.ai

**Comment by tianweidut** [comment]
- some sdk tune: https://github.com/star-whale/starwhale/issues/457
- example code comment:
  - https://github.com/star-whale/starwhale/blob/50d62391eaeb6f2c81d8e2457b9546cd29875d40/example/cifar10/code/ppl.py#L24
  - https://github.com/star-whale/starwhale/blob/50d62391eaeb6f2c81d8e2457b9546cd29875d40/example/PennFudanPed/code/ppl.py#L29

![image](https://user-images.githubusercontent.com/590748/171422144-b97f8ead-c5be-4108-af3c-3df7504491ed.png)
 
If `ignore_error=True`, PipelineHandler will ignore one iteration exception.  cc @anda-ren
