### ISSUE TITLE
controller /api/v1/project/{project_id}/model/{model_id} doesn't work

### ISSUE THREAD

**Issue by tianweidut** [star-whale/starwhale#462]
**Describe the bug**
when we call some urls，the results are the same, it does not show the the specified versionid info. 
 - http://console.pre.intra.starwhale.ai/api/v1/project/1/model/1?versionId=30
 - http://console.pre.intra.starwhale.ai/api/v1/project/1/model/1?versionId=31
 - http://console.pre.intra.starwhale.ai/api/v1/project/1/model/1?versionId=29

the result: 
```
{
  "code": "success",
  "message": "Success",
  "data": {
    "swmpId": null,
    "swmpName": null,
    "versionName": "gm4dsnjwmi3tinrtmftdgyjzmrrho5q",
    "versionTag": null,
    "versionMeta": "mnist:gm4dsnjwmi3tinrtmftdgyjzmrrho5q",
    "createdTime": 1654058132000,
    "files": [
      {
        "name": "gm4dsnjwmi3tinrtmftdgyjzmrrho5q.swmp",
        "size": "4.61 MB"
      }
    ]
  }
}
```

**To Reproduce**
[](http://console.pre.intra.starwhale.ai/swagger-ui/index.html#/Model/listModelVersion)

**Comment by dreamlandliu** [comment]
use versionUrl instead of versionId
