### ISSUE TITLE
decimal numbers overlap with each other on confusion matrics

### ISSUE THREAD

**Issue by anda-ren** [star-whale/starwhale#566]
**Describe the bug**
decimal numbers overlap with each other

**To Reproduce**
http://console.pre.intra.starwhale.ai/projects/1/jobs/26/results

**Expected behavior**

**Environment**

**Comment by waynelwz** [comment]
![image](https://user-images.githubusercontent.com/100347187/175007023-dea4b60c-ff54-442a-accd-d1414c118c6b.png)

#625  fixed , to be release
