### ISSUE TITLE
extend dataset files filter

### ISSUE THREAD

**Issue by anda-ren** [star-whale/starwhale#609]
Some datasets may specify files of test set by a file. Such as SpeechCommands dataset specifies the test files in a `testing_list.txt` file.

content fragment in `testing_list.txt`:
```
right/bb05582b_nohash_3.wav
right/97f4c236_nohash_2.wav
right/f2e59fea_nohash_3.wav
right/fdb5155e_nohash_2.wav
right/dc75148d_nohash_0.wav
right/3f170018_nohash_0.wav
```

**Current Behavior**
support [Path.rglob](https://docs.python.org/3/library/pathlib.html) filter

**Proposed Behavior**

- also support the filter paths specified in a file
- provide a doc for user to customize the file filter

**Solution Proposal**

**Comment by tianweidut** [comment]
use Starwhale Python Dataset SDK
