### ISSUE TITLE
Column management  and filter problem

### ISSUE THREAD

**Issue by lijing-susan** [star-whale/starwhale#640]
**Describe the bug**
① Manage colums: choose some columns after an empty save , the [save] does not work .
![image](https://user-images.githubusercontent.com/101299635/175465057-f96852c2-77a7-4073-ba1c-f126f76478cd.png)

② Add filter: the filtered results do not display overall, but  in different pages with blank rows. 
![image](https://user-images.githubusercontent.com/101299635/175464828-2dce8832-4257-4ae8-bf6a-be253be6decc.png)
![image](https://user-images.githubusercontent.com/101299635/175464898-604b7b1e-1aaf-4198-85bb-9b3ec7ce3a62.png)

③ the position of checkbox look strange, it seems that the positon of checkbox has also been saved with the columns.
![image](https://user-images.githubusercontent.com/101299635/175466148-7478e81e-1a42-4f7e-9b6f-c01036d4e30e.png)

**To Reproduce**

**Expected behavior**

**Environment**

**Comment by waynelwz** [comment]
fixed, check on next version
