### ISSUE TITLE
Controller support scheduling tasks based on K8s workload status

### ISSUE THREAD

**Issue by jialeicui** [star-whale/starwhale#781]
**Current Behavior**
based on agent reporting

**Proposed Behavior**
Controller support scheduling tasks based on K8s workload status
- deal with K8s job status
  - https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#jobstatus-v1-batch
  - https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-conditions
- retry logic triggered by users
- log collection
- K8s job cleanup ( manually or https://kubernetes.io/docs/concepts/workloads/controllers/job/#ttl-mechanism-for-finished-jobs)

**Comment by anda-ren** [comment]
done
- #817 
- #806 
- #805 
- #792 
- #785 
- #782
