### ISSUE TITLE
The header menu is not linked to the exact location

### ISSUE THREAD

**Issue by Cellen-Lee** [star-whale/starwhale#934]
**Describe the bug**
The header menu is not linked to the exact location.

**To Reproduce**
![link](https://user-images.githubusercontent.com/76032077/185381148-2a2306e8-6f40-4ac4-8fb9-f4d867bb631e.gif)

**Expected behavior**

**Environment**
https://starwhale.cn/product-intro#model
Occasional.

**Comment by waynelwz** [comment]
fixed, check online
